[[NASM]]
arch = "aarch64"
git-tree-sha1 = "d5ea077fa58f47e34864af3f19b3638d728b1ad4"
os = "macos"

    [[NASM.download]]
    sha256 = "4c19ecce1bde164cbd0d7847f39e6fc60962715aacc89ddca746e5050a16f70a"
    url = "https://github.com/JuliaBinaryWrappers/NASM_jll.jl/releases/download/NASM-v2.16.3+0/NASM.v2.16.3.aarch64-apple-darwin.tar.gz"
[[NASM]]
arch = "aarch64"
git-tree-sha1 = "fca850d3f118df1db9660bca84095e12b9b7d5f1"
libc = "glibc"
os = "linux"

    [[NASM.download]]
    sha256 = "0e95e85fa99e2ab69cc81c3a64a0d47410551d9c5c32d4cc37ee6f9b5a1b302a"
    url = "https://github.com/JuliaBinaryWrappers/NASM_jll.jl/releases/download/NASM-v2.16.3+0/NASM.v2.16.3.aarch64-linux-gnu.tar.gz"
[[NASM]]
arch = "aarch64"
git-tree-sha1 = "c885c12ce349c993f12aa3c97bc722198effc153"
libc = "musl"
os = "linux"

    [[NASM.download]]
    sha256 = "c3fa8b2413ca0093d2accf2ae02387105de5bf6b7d97329c8e721517736c6a04"
    url = "https://github.com/JuliaBinaryWrappers/NASM_jll.jl/releases/download/NASM-v2.16.3+0/NASM.v2.16.3.aarch64-linux-musl.tar.gz"
[[NASM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "99287c081c617a48c40bef1d08276cb27126fd3a"
libc = "glibc"
os = "linux"

    [[NASM.download]]
    sha256 = "0b1b40a0be9e794692b660140b2a11adceb3a18ef393ba572bb3291e1bcb148e"
    url = "https://github.com/JuliaBinaryWrappers/NASM_jll.jl/releases/download/NASM-v2.16.3+0/NASM.v2.16.3.armv6l-linux-gnueabihf.tar.gz"
[[NASM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "04dbb310d97588f75c3b2ce500240d9261ca2477"
libc = "musl"
os = "linux"

    [[NASM.download]]
    sha256 = "ea6728d3c136f777c498e83e21b51802c01f56f02c312368eaf48cd5a5fe66a6"
    url = "https://github.com/JuliaBinaryWrappers/NASM_jll.jl/releases/download/NASM-v2.16.3+0/NASM.v2.16.3.armv6l-linux-musleabihf.tar.gz"
[[NASM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "639d7c391df06be2355c6f5f378283f7982a0a12"
libc = "glibc"
os = "linux"

    [[NASM.download]]
    sha256 = "d2f2c2ebc2415303f9f22a27a846b0f4cf69198db59ce886dd995410080f70a8"
    url = "https://github.com/JuliaBinaryWrappers/NASM_jll.jl/releases/download/NASM-v2.16.3+0/NASM.v2.16.3.armv7l-linux-gnueabihf.tar.gz"
[[NASM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d6210887dd7148c4aaead21f4b0fc6b42f6a09ab"
libc = "musl"
os = "linux"

    [[NASM.download]]
    sha256 = "03d4d20573c7f226ba677c9d73b9e59cb2f9f333e6b92a9065766a2cd10be18f"
    url = "https://github.com/JuliaBinaryWrappers/NASM_jll.jl/releases/download/NASM-v2.16.3+0/NASM.v2.16.3.armv7l-linux-musleabihf.tar.gz"
[[NASM]]
arch = "i686"
git-tree-sha1 = "842ff5f77ad99d10aa755d1360fad8d85f884386"
libc = "glibc"
os = "linux"

    [[NASM.download]]
    sha256 = "58cebe36de6c80bfa6f5b5fd3155b3b402c8027253fc07ba936fa4198851cab9"
    url = "https://github.com/JuliaBinaryWrappers/NASM_jll.jl/releases/download/NASM-v2.16.3+0/NASM.v2.16.3.i686-linux-gnu.tar.gz"
[[NASM]]
arch = "i686"
git-tree-sha1 = "313ec8c5bbab523264ca4a3b89181d5383dea872"
libc = "musl"
os = "linux"

    [[NASM.download]]
    sha256 = "66e1389dfd4396f6ce4326cc4114605946ad6132642e1c2c5c3f7a0ee4b86411"
    url = "https://github.com/JuliaBinaryWrappers/NASM_jll.jl/releases/download/NASM-v2.16.3+0/NASM.v2.16.3.i686-linux-musl.tar.gz"
[[NASM]]
arch = "i686"
git-tree-sha1 = "d15381b7ff3a338a23010ab73402af540407cb8e"
os = "windows"

    [[NASM.download]]
    sha256 = "f2c58c9845bb96901ef5ad0585092dd30bf6278305f4f42ded928ec53057bcfa"
    url = "https://github.com/JuliaBinaryWrappers/NASM_jll.jl/releases/download/NASM-v2.16.3+0/NASM.v2.16.3.i686-w64-mingw32.tar.gz"
[[NASM]]
arch = "powerpc64le"
git-tree-sha1 = "be321be63aa4c0a33ebf8031b597ccaaa39f2ed3"
libc = "glibc"
os = "linux"

    [[NASM.download]]
    sha256 = "e66fcc2cff72377dc64539e430d0862d065199a3ab7f10efd6a846f0b58cfec2"
    url = "https://github.com/JuliaBinaryWrappers/NASM_jll.jl/releases/download/NASM-v2.16.3+0/NASM.v2.16.3.powerpc64le-linux-gnu.tar.gz"
[[NASM]]
arch = "x86_64"
git-tree-sha1 = "ac632215619fd4aee4cc9c763288ae1de9ff6bd8"
os = "macos"

    [[NASM.download]]
    sha256 = "c6ce75e93847970dedc38c58d72ee18643e985c681319aee8e63c48383a29ef2"
    url = "https://github.com/JuliaBinaryWrappers/NASM_jll.jl/releases/download/NASM-v2.16.3+0/NASM.v2.16.3.x86_64-apple-darwin.tar.gz"
[[NASM]]
arch = "x86_64"
git-tree-sha1 = "7b6c24c284b276db9b31a1593037a8597a40090c"
libc = "glibc"
os = "linux"

    [[NASM.download]]
    sha256 = "3274ac04393dab158591518946074eab45407f3ea64b3e097acfb95289f7f854"
    url = "https://github.com/JuliaBinaryWrappers/NASM_jll.jl/releases/download/NASM-v2.16.3+0/NASM.v2.16.3.x86_64-linux-gnu.tar.gz"
[[NASM]]
arch = "x86_64"
git-tree-sha1 = "5e29f6bb6efda0e8b34e98ec7e68eab46dec449c"
libc = "musl"
os = "linux"

    [[NASM.download]]
    sha256 = "17d089fe22299dca2cf7ac5fe3a1bb41b6fc11df8ada78c34318ecdefc96733f"
    url = "https://github.com/JuliaBinaryWrappers/NASM_jll.jl/releases/download/NASM-v2.16.3+0/NASM.v2.16.3.x86_64-linux-musl.tar.gz"
[[NASM]]
arch = "x86_64"
git-tree-sha1 = "17a77d68b930617ef833cc1eeaf9cabce5085866"
os = "freebsd"

    [[NASM.download]]
    sha256 = "68f5c8156441e7e4eed64bf45bd931b176328b2cb03b0b5f5b38c59e2640a94b"
    url = "https://github.com/JuliaBinaryWrappers/NASM_jll.jl/releases/download/NASM-v2.16.3+0/NASM.v2.16.3.x86_64-unknown-freebsd.tar.gz"
[[NASM]]
arch = "x86_64"
git-tree-sha1 = "2677f10e35963d4f5cd4c14cd53b857be1d29faf"
os = "windows"

    [[NASM.download]]
    sha256 = "4c93810eaa481abce158abd664fd020b2dc824f7c1b3990051cea86d20a1cab9"
    url = "https://github.com/JuliaBinaryWrappers/NASM_jll.jl/releases/download/NASM-v2.16.3+0/NASM.v2.16.3.x86_64-w64-mingw32.tar.gz"
