[[NASM]]
arch = "aarch64"
git-tree-sha1 = "86562b13dd6b28df88afad52a2c61e023582725b"
os = "macos"

    [[NASM.download]]
    sha256 = "c607df5cbf58dc0a947540624a5192025e3bbc89f2c67c9933309cffce721f50"
    url = "https://github.com/JuliaBinaryWrappers/NASM_jll.jl/releases/download/NASM-v2.16.1+0/NASM.v2.16.1.aarch64-apple-darwin.tar.gz"
[[NASM]]
arch = "aarch64"
git-tree-sha1 = "6cad9e10c0ca9097661ba64bec2d10232e0511a0"
libc = "glibc"
os = "linux"

    [[NASM.download]]
    sha256 = "64eec442b25b79eaf21eb15c5b14674bcf25ececf8b46cb64257fca7fcac6425"
    url = "https://github.com/JuliaBinaryWrappers/NASM_jll.jl/releases/download/NASM-v2.16.1+0/NASM.v2.16.1.aarch64-linux-gnu.tar.gz"
[[NASM]]
arch = "aarch64"
git-tree-sha1 = "0ec28b1bebe7dbcada404294b023163aecc7af69"
libc = "musl"
os = "linux"

    [[NASM.download]]
    sha256 = "46c528734b84910d3b20c188c3b9659b1eb6a3347b9c7116cf9dbe6a98ec79dd"
    url = "https://github.com/JuliaBinaryWrappers/NASM_jll.jl/releases/download/NASM-v2.16.1+0/NASM.v2.16.1.aarch64-linux-musl.tar.gz"
[[NASM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f1c8eb3af113c5f20cb6771b063026407bb17c74"
libc = "glibc"
os = "linux"

    [[NASM.download]]
    sha256 = "5f5a341db60cee5f124080079bc034bbc2ee8961762109e58858593119b2d2e6"
    url = "https://github.com/JuliaBinaryWrappers/NASM_jll.jl/releases/download/NASM-v2.16.1+0/NASM.v2.16.1.armv6l-linux-gnueabihf.tar.gz"
[[NASM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "567cfbe7da73973de3c9589055ac8bc656c57754"
libc = "musl"
os = "linux"

    [[NASM.download]]
    sha256 = "5eaa9dd7bc83143f1afe611941003f62dbb124200b9a4757ea7d9adc8fa79b1d"
    url = "https://github.com/JuliaBinaryWrappers/NASM_jll.jl/releases/download/NASM-v2.16.1+0/NASM.v2.16.1.armv6l-linux-musleabihf.tar.gz"
[[NASM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "12270f5966487531b064519d42e1e3a896c5ec98"
libc = "glibc"
os = "linux"

    [[NASM.download]]
    sha256 = "d960f858608e02d60fcc432b8c554b717430e7b1a59c6f2141a405a56e44aecc"
    url = "https://github.com/JuliaBinaryWrappers/NASM_jll.jl/releases/download/NASM-v2.16.1+0/NASM.v2.16.1.armv7l-linux-gnueabihf.tar.gz"
[[NASM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "81d655aae564db2d8934f7a30ce508980f1a4aa6"
libc = "musl"
os = "linux"

    [[NASM.download]]
    sha256 = "82220e232db4024a503608dbaee650d5ce40a1e1262671cd476280a8bfc4b7bd"
    url = "https://github.com/JuliaBinaryWrappers/NASM_jll.jl/releases/download/NASM-v2.16.1+0/NASM.v2.16.1.armv7l-linux-musleabihf.tar.gz"
[[NASM]]
arch = "i686"
git-tree-sha1 = "31f67d3f0ad7ee71a9b92c2be8b1a747a27dad47"
libc = "glibc"
os = "linux"

    [[NASM.download]]
    sha256 = "06c05fea20f788e74f790bd1054dfc4459d2f8af05fcee963768b6502b66575c"
    url = "https://github.com/JuliaBinaryWrappers/NASM_jll.jl/releases/download/NASM-v2.16.1+0/NASM.v2.16.1.i686-linux-gnu.tar.gz"
[[NASM]]
arch = "i686"
git-tree-sha1 = "0c287a3d195e783fd36d224f35ff334dfc2692c3"
libc = "musl"
os = "linux"

    [[NASM.download]]
    sha256 = "35616b7fee512ceda0d39bf4f0564d617f37bd4ddab9970a60ee2d3d953267d7"
    url = "https://github.com/JuliaBinaryWrappers/NASM_jll.jl/releases/download/NASM-v2.16.1+0/NASM.v2.16.1.i686-linux-musl.tar.gz"
[[NASM]]
arch = "i686"
git-tree-sha1 = "71f9c7a73bdef387d8c185902741ff6ffb80211b"
os = "windows"

    [[NASM.download]]
    sha256 = "39604e5349e989d6d2e4b741854fbf95ae769b435f2ca6f26a7020e62b0e3db0"
    url = "https://github.com/JuliaBinaryWrappers/NASM_jll.jl/releases/download/NASM-v2.16.1+0/NASM.v2.16.1.i686-w64-mingw32.tar.gz"
[[NASM]]
arch = "powerpc64le"
git-tree-sha1 = "12b35b5d5cbfbd4fb5d67c9507811920132a9219"
libc = "glibc"
os = "linux"

    [[NASM.download]]
    sha256 = "f9bda893f8b0c5b32bd772b583875baa31b31760d1b073dae2ff7ea67bcd799a"
    url = "https://github.com/JuliaBinaryWrappers/NASM_jll.jl/releases/download/NASM-v2.16.1+0/NASM.v2.16.1.powerpc64le-linux-gnu.tar.gz"
[[NASM]]
arch = "x86_64"
git-tree-sha1 = "5965aad501ab16289f0e1411d3aef6c4011eaa28"
os = "macos"

    [[NASM.download]]
    sha256 = "f8ab3ea5cf6a11fcdd9f9c6d3a41f9cf74874ce04928e6010d7c6f7e82c9a823"
    url = "https://github.com/JuliaBinaryWrappers/NASM_jll.jl/releases/download/NASM-v2.16.1+0/NASM.v2.16.1.x86_64-apple-darwin.tar.gz"
[[NASM]]
arch = "x86_64"
git-tree-sha1 = "74eba01770779387e0e4dd24b32e0bea7c1223c6"
libc = "glibc"
os = "linux"

    [[NASM.download]]
    sha256 = "d63563dd07f360612be9626a4b12a3738e89298d8ebb5375d3f435158d46fea3"
    url = "https://github.com/JuliaBinaryWrappers/NASM_jll.jl/releases/download/NASM-v2.16.1+0/NASM.v2.16.1.x86_64-linux-gnu.tar.gz"
[[NASM]]
arch = "x86_64"
git-tree-sha1 = "3e5ad4ec552b55551c14049f001d9e1420875467"
libc = "musl"
os = "linux"

    [[NASM.download]]
    sha256 = "bbb953cbf7275f8c6b5cf072596187693f63a37439c5e75703d4e024e760cdf0"
    url = "https://github.com/JuliaBinaryWrappers/NASM_jll.jl/releases/download/NASM-v2.16.1+0/NASM.v2.16.1.x86_64-linux-musl.tar.gz"
[[NASM]]
arch = "x86_64"
git-tree-sha1 = "54d1e3382e4d40fad6916c37fb3a1eed50126895"
os = "freebsd"

    [[NASM.download]]
    sha256 = "22f1ccef4731721377c0f59b14b1157bd912094249dcf8644c3a36af3f083db9"
    url = "https://github.com/JuliaBinaryWrappers/NASM_jll.jl/releases/download/NASM-v2.16.1+0/NASM.v2.16.1.x86_64-unknown-freebsd.tar.gz"
[[NASM]]
arch = "x86_64"
git-tree-sha1 = "1e59a369196ff8178cdb3dd4339039e32c35109c"
os = "windows"

    [[NASM.download]]
    sha256 = "56bd69bb08839f3413df19ecd7e87154fc26389227a1cefa3537a89f4f30e20b"
    url = "https://github.com/JuliaBinaryWrappers/NASM_jll.jl/releases/download/NASM-v2.16.1+0/NASM.v2.16.1.x86_64-w64-mingw32.tar.gz"
