[[NASM]]
arch = "aarch64"
git-tree-sha1 = "26ff020ea0fd4e4616e205f27c9678bf6acc3618"
os = "macos"

    [[NASM.download]]
    sha256 = "20c77e19d5087f39c46676bcf36bd19c038710b86204fb7455010f0303df16b7"
    url = "https://github.com/JuliaBinaryWrappers/NASM_jll.jl/releases/download/NASM-v3.2.0+0/NASM.v3.2.0.aarch64-apple-darwin.tar.gz"
[[NASM]]
arch = "aarch64"
git-tree-sha1 = "6e7f4ee43aca23dea341dff5daf1e179ddc2593f"
libc = "glibc"
os = "linux"

    [[NASM.download]]
    sha256 = "3fdb2a07641b2f0e042c4222458b2cf2a0e659542e7320aef03cfbed33dbf3a3"
    url = "https://github.com/JuliaBinaryWrappers/NASM_jll.jl/releases/download/NASM-v3.2.0+0/NASM.v3.2.0.aarch64-linux-gnu.tar.gz"
[[NASM]]
arch = "aarch64"
git-tree-sha1 = "a242e08e43c8c4e202f41227ef74f264535d06c8"
libc = "musl"
os = "linux"

    [[NASM.download]]
    sha256 = "2be55f3fdbb91bc20916dc305ea3fbfc52510e889ec89cf33abd19b058a2de33"
    url = "https://github.com/JuliaBinaryWrappers/NASM_jll.jl/releases/download/NASM-v3.2.0+0/NASM.v3.2.0.aarch64-linux-musl.tar.gz"
[[NASM]]
arch = "aarch64"
git-tree-sha1 = "9b18525ed201f84dd8ca4b0c0285e2841e9b57ad"
os = "freebsd"

    [[NASM.download]]
    sha256 = "b6c932155d4dadd31cfd01438df7b10a6724352b311d9eac1607dac0034d0b90"
    url = "https://github.com/JuliaBinaryWrappers/NASM_jll.jl/releases/download/NASM-v3.2.0+0/NASM.v3.2.0.aarch64-unknown-freebsd.tar.gz"
[[NASM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4621f864e1a14611bc5cfc329e347856cd5ce035"
libc = "glibc"
os = "linux"

    [[NASM.download]]
    sha256 = "b7ca959db1d4e8676693f2a39b0b21b8abeafc01c36b64f6d3c5361ee075694f"
    url = "https://github.com/JuliaBinaryWrappers/NASM_jll.jl/releases/download/NASM-v3.2.0+0/NASM.v3.2.0.armv6l-linux-gnueabihf.tar.gz"
[[NASM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2f90101772b66739c383ec070d425fef3e059b34"
libc = "musl"
os = "linux"

    [[NASM.download]]
    sha256 = "36b197e9a017c5dcf7de8c8b76936ec39bb387bf7bc82a66b35511176f77e829"
    url = "https://github.com/JuliaBinaryWrappers/NASM_jll.jl/releases/download/NASM-v3.2.0+0/NASM.v3.2.0.armv6l-linux-musleabihf.tar.gz"
[[NASM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "01750258245b07935d26513d85479ddf34e4dee1"
libc = "glibc"
os = "linux"

    [[NASM.download]]
    sha256 = "f66f24d1b54e607ba70be0d1f06e485f8987b276ac368bfa1760231994bbb448"
    url = "https://github.com/JuliaBinaryWrappers/NASM_jll.jl/releases/download/NASM-v3.2.0+0/NASM.v3.2.0.armv7l-linux-gnueabihf.tar.gz"
[[NASM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2d3644edd162087bd99a9c223719454140b5ab6b"
libc = "musl"
os = "linux"

    [[NASM.download]]
    sha256 = "e735beebff711534308e0a132ee358c6f4dcfa0fcd39d6c900f5b28b7096147e"
    url = "https://github.com/JuliaBinaryWrappers/NASM_jll.jl/releases/download/NASM-v3.2.0+0/NASM.v3.2.0.armv7l-linux-musleabihf.tar.gz"
[[NASM]]
arch = "i686"
git-tree-sha1 = "e86f0b0cd7abe9fbe1ec0c826e6c38d0f9d48235"
libc = "glibc"
os = "linux"

    [[NASM.download]]
    sha256 = "c278295a14343783c0ebb1be1f8e882f2f4883e107131a139c74cd8a3444487b"
    url = "https://github.com/JuliaBinaryWrappers/NASM_jll.jl/releases/download/NASM-v3.2.0+0/NASM.v3.2.0.i686-linux-gnu.tar.gz"
[[NASM]]
arch = "i686"
git-tree-sha1 = "7789a07f088d79ae5c5b628805aa82cbbd2a3578"
libc = "musl"
os = "linux"

    [[NASM.download]]
    sha256 = "81f4f30ad079f098fa0f7da0bcfb44f9842c9cbe3a4078fbb645a69a9c92d9ec"
    url = "https://github.com/JuliaBinaryWrappers/NASM_jll.jl/releases/download/NASM-v3.2.0+0/NASM.v3.2.0.i686-linux-musl.tar.gz"
[[NASM]]
arch = "i686"
git-tree-sha1 = "76325ed2156a58948dadb2169e0dcda3fc9eef46"
os = "windows"

    [[NASM.download]]
    sha256 = "4197f52c5c3a565019badd8f4d2bcc64608b6d9ef53a53ba0e9c76495c61b441"
    url = "https://github.com/JuliaBinaryWrappers/NASM_jll.jl/releases/download/NASM-v3.2.0+0/NASM.v3.2.0.i686-w64-mingw32.tar.gz"
[[NASM]]
arch = "powerpc64le"
git-tree-sha1 = "967fae4a81712ee432fa5b1f2216716e9f119126"
libc = "glibc"
os = "linux"

    [[NASM.download]]
    sha256 = "ab46b8565b17fc6797da62947e67f533b7cb5d30761241cb8dfb9c1a8db884c5"
    url = "https://github.com/JuliaBinaryWrappers/NASM_jll.jl/releases/download/NASM-v3.2.0+0/NASM.v3.2.0.powerpc64le-linux-gnu.tar.gz"
[[NASM]]
arch = "riscv64"
git-tree-sha1 = "e9be39da9d69f9e839d2a1afae51d3cde51fedda"
libc = "glibc"
os = "linux"

    [[NASM.download]]
    sha256 = "75ce0f3e453d6ffcfeb30ecf7de74f01cf56d7f26f09c43fa052d3443051ef10"
    url = "https://github.com/JuliaBinaryWrappers/NASM_jll.jl/releases/download/NASM-v3.2.0+0/NASM.v3.2.0.riscv64-linux-gnu.tar.gz"
[[NASM]]
arch = "x86_64"
git-tree-sha1 = "03f1df28f186b63add7a38dc423c6c84c4e0158f"
os = "macos"

    [[NASM.download]]
    sha256 = "bbffe3ef36f9ba1473005bb5178dd3bbe00b31778963729b42ab5ec19662f212"
    url = "https://github.com/JuliaBinaryWrappers/NASM_jll.jl/releases/download/NASM-v3.2.0+0/NASM.v3.2.0.x86_64-apple-darwin.tar.gz"
[[NASM]]
arch = "x86_64"
git-tree-sha1 = "43f8bedf7dd68a4d9fc7a9c4a49cc01e435fdacf"
libc = "glibc"
os = "linux"

    [[NASM.download]]
    sha256 = "a4ad46ca160e516de9c1b3705b4f909a9a6154b53631890c74dca22ab749a13d"
    url = "https://github.com/JuliaBinaryWrappers/NASM_jll.jl/releases/download/NASM-v3.2.0+0/NASM.v3.2.0.x86_64-linux-gnu.tar.gz"
[[NASM]]
arch = "x86_64"
git-tree-sha1 = "c19102a8d33cd6b2c67df95f0135883c5602f0a0"
libc = "musl"
os = "linux"

    [[NASM.download]]
    sha256 = "f58b0e08170016a5278d4772619b1b7a1598b20ef6c8ccc0f78b6e78ded06259"
    url = "https://github.com/JuliaBinaryWrappers/NASM_jll.jl/releases/download/NASM-v3.2.0+0/NASM.v3.2.0.x86_64-linux-musl.tar.gz"
[[NASM]]
arch = "x86_64"
git-tree-sha1 = "8fd36a8b268a928f6a2e99208f05336000c00361"
os = "freebsd"

    [[NASM.download]]
    sha256 = "c1846797aa329885a4217166e8c7d597043d052f14ca25a18c3ace0121fb8ed4"
    url = "https://github.com/JuliaBinaryWrappers/NASM_jll.jl/releases/download/NASM-v3.2.0+0/NASM.v3.2.0.x86_64-unknown-freebsd.tar.gz"
[[NASM]]
arch = "x86_64"
git-tree-sha1 = "1ba12f7c03557c4dcec99deb47ec545df2339590"
os = "windows"

    [[NASM.download]]
    sha256 = "42b2f8aaa10582fc9ee59c8de33b807abdcbba90d254532d1625a9bfb20a6929"
    url = "https://github.com/JuliaBinaryWrappers/NASM_jll.jl/releases/download/NASM-v3.2.0+0/NASM.v3.2.0.x86_64-w64-mingw32.tar.gz"
