# Autogenerated wrapper script for NASM_jll for aarch64-unknown-freebsd
export nasm, ndisasm

using Zlib_jll
JLLWrappers.@generate_wrapper_header("NASM")
JLLWrappers.@declare_executable_product(nasm)
JLLWrappers.@declare_executable_product(ndisasm)
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll)
    JLLWrappers.@init_executable_product(
        nasm,
        "bin/nasm",
    )

    JLLWrappers.@init_executable_product(
        ndisasm,
        "bin/ndisasm",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
