# Autogenerated wrapper script for NASM_jll for x86_64-w64-mingw32
export nasm, ndisasm

JLLWrappers.@generate_wrapper_header("NASM")
JLLWrappers.@declare_executable_product(nasm)
JLLWrappers.@declare_executable_product(ndisasm)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        nasm,
        "bin\\nasm.exe",
    )

    JLLWrappers.@init_executable_product(
        ndisasm,
        "bin\\ndisasm.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
